" knuts' .vimrc stolen from varius places
" most notably stevelosh.com
"
" Preamble ---------------------------------------------------------------- {{{

filetype off
syntax on
execute pathogen#incubate()
filetype plugin indent on
set nocompatible


" }}}

" gvim-options ------------------------------------------------------------ {{{


if has('gui_running')
	autocmd GUIEnter * simalt ~x
	set guioptions-=T  " no toolbar
	set guioptions-=m " Removes menu
	set guifont=Consolas
	set nobackup
	"set backup
	"set backupdir=C:\\vimptemp
else

	" Store temporary files in a central spot
	set backup
	set backupdir=~/.vim-tmp//,~/.tmp//,~/tmp//,/var/tmp//,/tmp//
	set directory=~/.vim-tmp//,~/.tmp//,~/tmp//,/var/tmp//,/tmp//

endif



" }}}
" Basic options ----------------------------------------------------------- {{{

" Options that need a specific version

if (version >= 730)
	set colorcolumn=85
	" Erstatter \Pi med unicode-tegnet i mathmode i latex bl.a.
	set conceallevel=2
	hi Conceal guibg=NONE ctermbg=NONE
endif

let mapleader="\<Space>"

set hidden
set encoding=utf-8
set modelines=0
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set vb t_vb=
set list
set listchars=tab:\ \ 
set t_Co=256
" Attempt to get 256 colors whenever possible
if &term =~ "xterm"
	set t_Co=256
	if has("terminfo")
		let &t_Sf=nr2char(27).'[3%p1%dm'
		let &t_Sb=nr2char(27).'[4%p1%dm'
	else
		let &t_Sf=nr2char(27).'[3%dm'
		let &t_Sb=nr2char(27).'[4%dm'
	endif
endif
set textwidth=80
set formatoptions=qrn1
set gdefault
set gdefault "Så slipper du slenge på /g på alt
set cursorline " hilighter aktiv linje
set wildmenu " viser forslag til :kommandoer
set wildmode=list:longest
set ttyfast
set showcmd
set visualbell
set number
set pastetoggle=<F3>


" vim-latex-ting
let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat='pdf'
let g:Tex_MultipleCompileFormats='dvi,pdf'
let g:Tex_ViewRule_pdf='evince &'
set backspace=indent,eol,start


filetype plugin on
"colorscheme molokai
colorscheme badwolf

" Spelling {{{
set spelllang=nb
" }}}
set noswapfile                    " It's 2012, Vim.


" }}}
" Searching and movement -------------------------------------------------- {{{

set ignorecase
set smartcase
set gdefault
set showmatch
set hlsearch
set incsearch
set virtualedit+=block

" Minimum number of lines between cursor and egde
set scrolloff=3
set sidescroll=1
set sidescrolloff=10


" }}}
" Mappings ---------------------------------------------------------------- {{{

" !
nnoremap <leader>w :w<cr>

" Change working directory
nnoremap <leader>cd :cd %:p:h<cr>

" Directional keys -------------------------------------------------------- {{{


" Split stuff
"vertical split and move to it
nnoremap <leader>v <C-w>v<C-w>l
" Window resizing
nnoremap <left> 5<c-w>>
nnoremap <right> 5<c-w><
nnoremap <up> 5<c-w>+
nnoremap <down> 5<c-w>-
" }}}

" j og k oppfører seg som du forventer også med wrappede linjer
nnoremap j gj
nnoremap k gk
" Det er så langt bort til <ESC> hallo
inoremap jj <ESC>

" Open a Quickfix window for the last search.
nnoremap <silent> <leader>/ :execute 'vimgrep /'.@/.'/g %'<CR>:copen<CR>

" Don't move on * (Just hilight the on the cursor)
nnoremap * *<c-o>


map <F2> :NERDTreeToggle<CR>

" Fuck you, help key.
noremap  <F1> :set invfullscreen<CR>
inoremap <F1> <ESC>:SET INVFULLSCREen<CR>A

" Fuck you too, manual key.
nnoremap K <nop>

" Fjerner hilight etter at du har søkt opp div
nnoremap <leader><space> :noh<cr>

"" very magic
nnoremap / /\v
vnoremap / /\v

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" tabedit vimrc
nnoremap <leader>ve :tabedit $MYVIMRC<CR>
" source vimrc
nnoremap <leader>vr :so $MYVIMRC<CR>

" ,N - toggle line numbers
function! ToggleLineNumbers() " {{{
	if &number
		set nonumber
	elseif &relativenumber
		set number
	else
		set relativenumber
	endif
endfunction 
" }}}
nnoremap <silent> <leader>N :call ToggleLineNumbers()<CR>


" }}}
" Highlight Word {{{
"
" This mini-plugin provides a few mappings for highlighting words temporarily.
"
" Sometimes you're looking at a hairy piece of code and would like a certain
" word or two to stand out temporarily.  You can search for it, but that only
" gives you one color of highlighting.  Now you can use <leader>N where N is
" a number from 1-6 to highlight the current word in a specific color.

function! HiInterestingWord(n) " {{{
    " Save our location.
    normal! mz

    " Yank the current word into the z register.
    normal! "zyiw

    " Calculate an arbitrary match ID.  Hopefully nothing else is using it.
    let mid = 86750 + a:n

    " Clear existing matches, but don't worry if they don't exist.
    silent! call matchdelete(mid)

    " Construct a literal pattern that has to match at boundaries.
    let pat = '\V\<' . escape(@z, '\') . '\>'

    " Actually match the words.
    call matchadd("InterestingWord" . a:n, pat, 1, mid)

    " Move back to our original location.
    normal! `z
endfunction " }}}

" Mappings {{{

nnoremap <silent> <leader>1 :call HiInterestingWord(1)<cr>
nnoremap <silent> <leader>2 :call HiInterestingWord(2)<cr>
nnoremap <silent> <leader>3 :call HiInterestingWord(3)<cr>
nnoremap <silent> <leader>4 :call HiInterestingWord(4)<cr>
nnoremap <silent> <leader>5 :call HiInterestingWord(5)<cr>
nnoremap <silent> <leader>6 :call HiInterestingWord(6)<cr>

" }}}
" Default Highlights {{{

hi def InterestingWord1 guifg=#000000 ctermfg=16 guibg=#ffa724 ctermbg=214
hi def InterestingWord2 guifg=#000000 ctermfg=16 guibg=#aeee00 ctermbg=154
hi def InterestingWord3 guifg=#000000 ctermfg=16 guibg=#8cffba ctermbg=121
hi def InterestingWord4 guifg=#000000 ctermfg=16 guibg=#b88853 ctermbg=137
hi def InterestingWord5 guifg=#000000 ctermfg=16 guibg=#ff9eb8 ctermbg=211
hi def InterestingWord6 guifg=#000000 ctermfg=16 guibg=#ff2c4b ctermbg=195

" }}}

" }}}

" Make behave ------------------------------------------------------------- {{{

" Keep search matches in the middle of the window and pulse the line when moving
" to them.
nnoremap n nzz
nnoremap N Nzz

" Easier to type, and I never use the default behavior.
noremap H ^
noremap L g_

" }}}
" Buffer movement --------------------------------------------------------- {{{

" ,bd - delete buffer
nnoremap <silent> <leader>bd :bdelete<CR>
" ,n - next buffer
nnoremap <silent> <leader>n :bnext<CR>
" ,p - previous buffer
nnoremap <silent> <leader>p :bprevious<CR>
" }}}
" }}}
" Folding ----------------------------------------------------------------- {{{
set foldlevelstart=0
" Make the current location sane.
nnoremap <c-cr> zvzt

" Make zO recursively open whatever top level fold we're in, no matter where the
" cursor happens to be.
nnoremap zO zCzO

" Use ,z to "focus" the current fold.
nnoremap <leader>z zMzvzz

" }}}
" Various filetype-specific stuff ----------------------------------------- {{{
" Python {{{

augroup ft_python
    au!

    au FileType python setlocal define=^\s*\\(def\\\\|class\\)
    au FileType man nnoremap <buffer> <cr> :q<cr>

    " Jesus tapdancing Christ, built-in Python syntax, you couldn't let me
    " override this in a normal way, could you?
    au FileType python if exists("python_space_error_highlight") | unlet python_space_error_highlight | endif

    au FileType python iabbrev <buffer> afo assert False, "Okay"

	nnoremap <leader>p :pyfile %<cr>
augroup END

" }}}
" LaTeX {{{

augroup ft_tex
	au!
	au FileType tex setlocal foldmethod=manual
augroup end

" }}}
" C {{{

augroup ft_c
    au!
    au FileType c setlocal foldmethod=manual
augroup END

" }}}
" QuickFix {{{

augroup ft_quickfix
    au!
    au Filetype qf setlocal colorcolumn=0 nolist nocursorline nowrap
augroup END

" }}}
" Vim {{{

augroup ft_vim
    au!

    au FileType vim setlocal foldmethod=marker
    au FileType help setlocal textwidth=78
    au BufWinEnter *.txt if &ft == 'help' | wincmd L | endif
augroup END

" }}}
" }}}
" Plugin settings --------------------------------------------------------- {{{
" Rainbow Parentheses {{{
nnoremap <leader>R :RainbowParenthesesToggle<cr>
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue4'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
" }}}
" Powerline -------------------------------------------------------------- {{{
set laststatus=2
"let g:Powerline_symbols='fancy'
set fillchars+=stl:\ ,stlnc:\
" }}}
" }}}
